apiVersion: v1
kind: Pod
metadata:
  name: anomalydetection
spec:
  containers:
  - name: anomalydetection
    image: {{ .Values.image.anomaly}}:{{.Values.image.version }}
    command:
    - sh
    - -c
    - "/opt/spark/bin/spark-submit 
        --master k8s://http://kube-apiserver-0-instance.kubernetes.mesos:9000 
        --deploy-mode cluster 
        --files http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/hdfs-site.xml,http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/core-site.xml
        --name anomaly --class {{ .Values.anomaly.main }}
        --conf spark.executor.instances=3 
        --conf spark.kubernetes.mountDependencies.filesDownloadDir=/etc/hadoop/conf
        --conf 'spark.driver.extraJavaOptions=-Dconfig.resource=application.conf'
        --conf spark.kubernetes.container.image={{ .Values.image.anomaly}}:{{.Values.image.version }}
        --conf spark.kubernetes.container.image.pullPolicy=Always
        local:///opt/spark/jars/{{ .Values.anomaly.jar}}
        -t nwout -b kafka-0-broker.kafka.autoip.dcos.thisdcos.directory:1025 -m 60 -k 150"
  restartPolicy: Never
