apiVersion: v1
kind: Pod
metadata:
  name: publisher
spec:
  containers:
  - name: publisher
    image: lightbend/publisher:v1.2.0
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget http://s3-eu-west-1.amazonaws.com/fdp-killrweather-data/data/data.zip -O /data-dir/data.zip; unzip /data-dir/data.zip -d /data-dir/
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}
