apiVersion: v1
kind: Pod
metadata:
  name: publisher
spec:
  containers:
  - name: publisher
    image: lightbend/publisher:1.2.0
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    # put the right url here
    - wget -O /data-dir/data.zip http://kubernetes.io unzip /data-dir/data.zip -d /data-dir/
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}
