# Default values for checkpointingchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# PVC information
pvc:
  name: spark-checkpointing-pvc
  size: 10Gi
  type: glusterfs-storage

