apiVersion: v1
kind: Pod
metadata:
  name: kstreamprocchart
spec:
  containers:
  - name: kstreamproctransformer
    image: {{ .Values.image.repository}}/{{ .Values.image.name}}:{{.Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
    env:          
    - name: "DIRECTORY_TO_WATCH"
      value: "/usr/share"
    - name: "KAFKA_BROKERS"
      value: {{ .Values.configuration.kafka.brokerlist}}
    - name: "INTERFACE_PROC"
      value: {{ .Values.configuration.rest.interface}}
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectory }} -O /data-dir/clarknet_access_log_Sep4.tgz; tar xvfz /data-dir/clarknet_access_log_Sep4.tgz -C /data-dir
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}


