# Default values for modelserverchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# data.zip location
data:
  datadirectory: http://s3-eu-west-1.amazonaws.com/fdp-killrweather-data/data/data.zip
# docker images
image:
  akka: lightbend/akkasvc
  kafka: lightbend/kafkasvc
  publisher: lightbend/publisher
  pullPolicy: IfNotPresent
  version: v1.2.0
# Server type. If akka - install akka implementation, otherwise - kafka implementation
server:
  type: akka