# Default values for anomaly detection chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# docker image
image:
  anomaly: lightbend/anomalydetection-k8s
  pullPolicy: Always
  version: 1.2.0

# assembly jars and main classes
anomaly:
  jar: anomalyDetection-assembly-1.2.0.jar
  main: com.lightbend.fdp.sample.nwintrusion.anomaly.SparkClustering
