# Default values for killrweather.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# data.zip location
data:
  datadirectory: http://s3-eu-west-1.amazonaws.com/fdp-killrweather-data/killrweather/data.zip
# docker images
image:
  grpc: lightbend/grpcclient
  http: lightbend/httpclient
  loader: lightbend/loader
  pullPolicy: Always
  version: 1.2.0
