apiVersion: v1
kind: Pod
metadata:
  name: modelserverpublisher
spec:
  containers:
  - name: modelserverpublisher
    image: {{ .Values.image.publisher}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    env:
      - name: KAFKA_BROKERS_LIST
        value: {{ .Values.configuration.kafka.brokerlist}}
      - name: DATA_PUBLISH_INTERVAL
        value: {{ .Values.configuration.publisher.data_publish_interval}}
      - name: MODEL_PUBLISH_INTERVAL
        value: {{ .Values.configuration.publisher.model_publish_interval}}
      - name: DATA_DIRECTORY
        value: {{ .Values.configuration.publisher.data_mount}}/data
      - name: DATA_FILENAME
        value: {{ .Values.configuration.publisher.data_file}}
    volumeMounts:
    - name: datadir
      mountPath: {{ .Values.configuration.publisher.data_mount}}
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectory }} -O {{ .Values.configuration.publisher.data_mount}}/data.zip; unzip {{ .Values.configuration.publisher.data_mount}}/data.zip -d {{ .Values.configuration.publisher.data_mount}}/
    volumeMounts:
    - name: datadir
      mountPath: {{ .Values.configuration.publisher.data_mount}}
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}
