apiVersion: v1
kind: Pod
metadata:
  name: modelserverpublisher
spec:
  containers:
  - name: modelserverpublisher
    image: {{ .Values.image.publisher}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectory }} -O /data-dir/data.zip; unzip /data-dir/data.zip -d /data-dir/
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}
