apiVersion: v1
kind: Pod
metadata:
  name: killrweatherdataloader
  labels:
    fdpmanager : visible
spec:
  containers:
  - name: killrweatherdataloader
    image: {{ .Values.image.loader}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectory }} -O /data-dir/data.zip; unzip /data-dir/data.zip -d /data-dir/
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}

{{ if eq .Values.components.http "yes" }}
-----
apiVersion: v1
kind: Pod
metadata:
  name: killrweatherhttpclient
  labels:
    fdpmanager : visible
spec:
  containers:
  - name: killrweatherhttpclient
    image: {{ .Values.image.http }}:{{.Values.image.version }}
{{ end }}

{{ if eq .Values.components.grpc "yes" }}
---------
apiVersion: v1
kind: Pod
metadata:
  name: killrweathergrpcclient
  labels:
    fdpmanager : visible
spec:
  containers:
  - name: killrweathergrpcclient
    image: {{ .Values.image.grpc }}:{{.Values.image.version }}
{{ end }}